language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-d2-webapp' ]; then cd .. && eval "mv $currentfolder generator-d2-webapp" && cd generator-d2-webapp; fi

